Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -27,11 +27,22 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
+    - name: Show GITHUB_SHA
+      run: echo "GITHUB_SHA is: $GITHUB_SHA"
+
     - name: Build Docker image
       run: |
         # Git commit hash'inin ilk 7 karakterini tag olarak kullan
         IMAGE_TAG="${GITHUB_SHA:0:7}"  # İlk 7 karakteri al
         echo "Using IMAGE_TAG: $IMAGE_TAG"  # Tag'i yazdırarak kontrol et
+        
+        # Eğer IMAGE_TAG boşsa hata ver
+        if [ -z "$IMAGE_TAG" ]; then
+          echo "ERROR: IMAGE_TAG is empty!"
+          exit 1
+        fi
+        
+        # Docker build işlemi
         docker build -t snilsumelis/hello-world-for-argocd:$IMAGE_TAG -f ./node-hello-world/Dockerfile ./node-hello-world
     
     - name: Push Docker image to Docker Hub
